# Generated by Django 3.2.5 on 2021-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$7OWikJ3VbzULfl3EhZvggY$S0+sDw+8oLJSP091CYhxNxQRtPmO5rrJw84Frv4S5Ag=', max_length=150),
            preserve_default=False,
        ),
    ]
