# Generated by Django 3.2.5 on 2021-08-25 15:58

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_minitask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minitask',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'khởi tạo'), (1, 'đang sửa đổi'), (2, 'đang kiểm định'), (3, 'đã hoàn thiện')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'khởi tạo'), (1, 'đang sửa đổi'), (2, 'đang kiểm định'), (3, 'đã hoàn thiện')], default=0),
        ),
    ]
