# Generated by Django 3.2.5 on 2021-08-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210825_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minitask',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_at',
        ),
    ]
