# Generated by Django 3.2.5 on 2021-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20210827_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minitask',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='minitask',
            name='start_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(),
        ),
    ]
