# Generated by Django 3.2.5 on 2021-08-28 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20210828_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minitask',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='minitask',
            name='start_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
