# Generated by Django 3.2.4 on 2021-07-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('D', 'hướng'), ('G', 'nhóm'), ('A', 'địa bàn')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='XFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN', 'khởi tạo'), ('ED', 'đang sửa đổi'), ('CH', 'đang kiểm định'), ('AP', 'đang phê duyệt'), ('DO', 'đã hoàn thiện')], default='ED', max_length=2)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('approvers', models.ManyToManyField(related_name='xfiles_can_approve', to=settings.AUTH_USER_MODEL)),
                ('checkers', models.ManyToManyField(related_name='xfiles_can_check', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('editors', models.ManyToManyField(related_name='xfiles_can_edit', to=settings.AUTH_USER_MODEL)),
                ('targets', models.ManyToManyField(to='hsmt.Target')),
            ],
        ),
        migrations.CreateModel(
            name='XFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('example_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XFileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_edited', models.DateField(blank=True, null=True)),
                ('date_checked', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='hsmt.xfile')),
            ],
        ),
        migrations.AddField(
            model_name='xfile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsmt.xfiletype'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
