# Generated by Django 3.2.4 on 2021-07-19 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfilechange',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xfilechange',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xfilechange',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
