# Generated by Django 3.2.5 on 2021-09-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0003_alter_attacklog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacklog',
            old_name='content',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='attacklog',
            old_name='name',
            new_name='result',
        ),
    ]
