# Generated by Django 3.2.5 on 2021-07-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0004_alter_xfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('name', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('attacker', models.TextField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_logs', to='hsmt.xfile')),
            ],
        ),
    ]
