# Generated by Django 3.2.5 on 2021-08-04 08:34

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0005_attacklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.PositiveIntegerField(choices=[('0', 'hướng'), ('1', 'nhóm'), ('2', 'địa bàn')]),
        ),
        migrations.AlterField(
            model_name='xfile',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'khởi tạo'), (1, 'đang sửa đổi'), (2, 'đang kiểm định'), (3, 'đang phê duyệt'), (4, 'đã hoàn thiện')], default=0, max_length=2, protected=True),
        ),
    ]
