# Generated by Django 3.2.5 on 2021-09-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0005_alter_attacklog_attacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacklog',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_logs', to='hsmt.xfile'),
        ),
    ]
