# Generated by Django 3.2.5 on 2021-08-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0007_auto_20210806_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'hướng'), (2, 'nhóm'), (3, 'địa bàn')]),
        ),
    ]
