# Generated by Django 3.2.5 on 2021-08-17 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hsmt', '0008_alter_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfile',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
