# Generated by Django 3.2.5 on 2021-08-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsmt', '0010_alter_xfile_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfilechange',
            name='date_submited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
